INSERT INTO countries (id, name, phone_code, emoji) VALUES ('1', 'Afghanistan', '93', '🇦🇫');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('2', 'Aland Islands', '+358-18', '🇦🇽');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('3', 'Albania', '355', '🇦🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('4', 'Algeria', '213', '🇩🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('5', 'American Samoa', '+1-684', '🇦🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('6', 'Andorra', '376', '🇦🇩');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('7', 'Angola', '244', '🇦🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('8', 'Anguilla', '+1-264', '🇦🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('9', 'Antarctica', '672', '🇦🇶');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('10', 'Antigua and Barbuda', '+1-268', '🇦🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('11', 'Argentina', '54', '🇦🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('12', 'Armenia', '374', '🇦🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('13', 'Aruba', '297', '🇦🇼');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('14', 'Australia', '61', '🇦🇺');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('15', 'Austria', '43', '🇦🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('16', 'Azerbaijan', '994', '🇦🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('18', 'Bahrain', '973', '🇧🇭');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('19', 'Bangladesh', '880', '🇧🇩');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('20', 'Barbados', '+1-246', '🇧🇧');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('21', 'Belarus', '375', '🇧🇾');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('22', 'Belgium', '32', '🇧🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('23', 'Belize', '501', '🇧🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('24', 'Benin', '229', '🇧🇯');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('25', 'Bermuda', '+1-441', '🇧🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('26', 'Bhutan', '975', '🇧🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('27', 'Bolivia', '591', '🇧🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('155', 'Bonaire, Sint Eustatius and Saba', '599', '🇧🇶');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('28', 'Bosnia and Herzegovina', '387', '🇧🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('29', 'Botswana', '267', '🇧🇼');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('30', 'Bouvet Island', '0055', '🇧🇻');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('31', 'Brazil', '55', '🇧🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('32', 'British Indian Ocean Territory', '246', '🇮🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('33', 'Brunei', '673', '🇧🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('34', 'Bulgaria', '359', '🇧🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('35', 'Burkina Faso', '226', '🇧🇫');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('36', 'Burundi', '257', '🇧🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('37', 'Cambodia', '855', '🇰🇭');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('38', 'Cameroon', '237', '🇨🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('39', 'Canada', '1', '🇨🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('40', 'Cape Verde', '238', '🇨🇻');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('41', 'Cayman Islands', '+1-345', '🇰🇾');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('42', 'Central African Republic', '236', '🇨🇫');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('43', 'Chad', '235', '🇹🇩');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('44', 'Chile', '56', '🇨🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('45', 'China', '86', '🇨🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('46', 'Christmas Island', '61', '🇨🇽');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('47', 'Cocos (Keeling) Islands', '61', '🇨🇨');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('48', 'Colombia', '57', '🇨🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('49', 'Comoros', '269', '🇰🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('50', 'Congo', '242', '🇨🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('52', 'Cook Islands', '682', '🇨🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('53', 'Costa Rica', '506', '🇨🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('54', 'Cote D''Ivoire (Ivory Coast)', '225', '🇨🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('55', 'Croatia', '385', '🇭🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('56', 'Cuba', '53', '🇨🇺');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('249', 'Curaçao', '599', '🇨🇼');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('57', 'Cyprus', '357', '🇨🇾');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('58', 'Czech Republic', '420', '🇨🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('51', 'Democratic Republic of the Congo', '243', '🇨🇩');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('59', 'Denmark', '45', '🇩🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('60', 'Djibouti', '253', '🇩🇯');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('61', 'Dominica', '+1-767', '🇩🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('62', 'Dominican Republic', '+1-809 and 1-829', '🇩🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('64', 'Ecuador', '593', '🇪🇨');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('65', 'Egypt', '20', '🇪🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('66', 'El Salvador', '503', '🇸🇻');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('67', 'Equatorial Guinea', '240', '🇬🇶');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('68', 'Eritrea', '291', '🇪🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('69', 'Estonia', '372', '🇪🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('212', 'Eswatini', '268', '🇸🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('70', 'Ethiopia', '251', '🇪🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('71', 'Falkland Islands', '500', '🇫🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('72', 'Faroe Islands', '298', '🇫🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('73', 'Fiji Islands', '679', '🇫🇯');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('74', 'Finland', '358', '🇫🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('75', 'France', '33', '🇫🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('76', 'French Guiana', '594', '🇬🇫');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('77', 'French Polynesia', '689', '🇵🇫');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('78', 'French Southern Territories', '262', '🇹🇫');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('79', 'Gabon', '241', '🇬🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('80', 'Gambia The', '220', '🇬🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('81', 'Georgia', '995', '🇬🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('82', 'Germany', '49', '🇩🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('83', 'Ghana', '233', '🇬🇭');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('84', 'Gibraltar', '350', '🇬🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('85', 'Greece', '30', '🇬🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('86', 'Greenland', '299', '🇬🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('87', 'Grenada', '+1-473', '🇬🇩');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('88', 'Guadeloupe', '590', '🇬🇵');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('89', 'Guam', '+1-671', '🇬🇺');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('90', 'Guatemala', '502', '🇬🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('91', 'Guernsey and Alderney', '+44-1481', '🇬🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('92', 'Guinea', '224', '🇬🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('93', 'Guinea-Bissau', '245', '🇬🇼');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('94', 'Guyana', '592', '🇬🇾');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('95', 'Haiti', '509', '🇭🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('96', 'Heard Island and McDonald Islands', '672', '🇭🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('97', 'Honduras', '504', '🇭🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('98', 'Hong Kong S.A.R.', '852', '🇭🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('99', 'Hungary', '36', '🇭🇺');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('100', 'Iceland', '354', '🇮🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('101', 'India', '91', '🇮🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('102', 'Indonesia', '62', '🇮🇩');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('103', 'Iran', '98', '🇮🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('104', 'Iraq', '964', '🇮🇶');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('105', 'Ireland', '353', '🇮🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('106', 'Israel', '972', '🇮🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('107', 'Italy', '39', '🇮🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('108', 'Jamaica', '+1-876', '🇯🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('109', 'Japan', '81', '🇯🇵');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('110', 'Jersey', '+44-1534', '🇯🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('111', 'Jordan', '962', '🇯🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('112', 'Kazakhstan', '7', '🇰🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('113', 'Kenya', '254', '🇰🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('114', 'Kiribati', '686', '🇰🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('248', 'Kosovo', '383', '🇽🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('117', 'Kuwait', '965', '🇰🇼');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('118', 'Kyrgyzstan', '996', '🇰🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('119', 'Laos', '856', '🇱🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('120', 'Latvia', '371', '🇱🇻');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('121', 'Lebanon', '961', '🇱🇧');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('122', 'Lesotho', '266', '🇱🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('123', 'Liberia', '231', '🇱🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('124', 'Libya', '218', '🇱🇾');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('125', 'Liechtenstein', '423', '🇱🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('126', 'Lithuania', '370', '🇱🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('127', 'Luxembourg', '352', '🇱🇺');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('128', 'Macau S.A.R.', '853', '🇲🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('130', 'Madagascar', '261', '🇲🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('131', 'Malawi', '265', '🇲🇼');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('132', 'Malaysia', '60', '🇲🇾');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('133', 'Maldives', '960', '🇲🇻');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('134', 'Mali', '223', '🇲🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('135', 'Malta', '356', '🇲🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('136', 'Man (Isle of)', '+44-1624', '🇮🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('137', 'Marshall Islands', '692', '🇲🇭');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('138', 'Martinique', '596', '🇲🇶');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('139', 'Mauritania', '222', '🇲🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('140', 'Mauritius', '230', '🇲🇺');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('141', 'Mayotte', '262', '🇾🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('142', 'Mexico', '52', '🇲🇽');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('143', 'Micronesia', '691', '🇫🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('144', 'Moldova', '373', '🇲🇩');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('145', 'Monaco', '377', '🇲🇨');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('146', 'Mongolia', '976', '🇲🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('147', 'Montenegro', '382', '🇲🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('148', 'Montserrat', '+1-664', '🇲🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('149', 'Morocco', '212', '🇲🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('150', 'Mozambique', '258', '🇲🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('151', 'Myanmar', '95', '🇲🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('152', 'Namibia', '264', '🇳🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('153', 'Nauru', '674', '🇳🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('154', 'Nepal', '977', '🇳🇵');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('156', 'Netherlands', '31', '🇳🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('157', 'New Caledonia', '687', '🇳🇨');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('158', 'New Zealand', '64', '🇳🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('159', 'Nicaragua', '505', '🇳🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('160', 'Niger', '227', '🇳🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('161', 'Nigeria', '234', '🇳🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('162', 'Niue', '683', '🇳🇺');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('163', 'Norfolk Island', '672', '🇳🇫');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('115', 'North Korea', '850', '🇰🇵');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('129', 'North Macedonia', '389', '🇲🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('164', 'Northern Mariana Islands', '+1-670', '🇲🇵');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('165', 'Norway', '47', '🇳🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('166', 'Oman', '968', '🇴🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('167', 'Pakistan', '92', '🇵🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('168', 'Palau', '680', '🇵🇼');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('169', 'Palestinian Territory Occupied', '970', '🇵🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('170', 'Panama', '507', '🇵🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('171', 'Papua New Guinea', '675', '🇵🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('172', 'Paraguay', '595', '🇵🇾');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('173', 'Peru', '51', '🇵🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('174', 'Philippines', '63', '🇵🇭');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('175', 'Pitcairn Island', '870', '🇵🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('176', 'Poland', '48', '🇵🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('177', 'Portugal', '351', '🇵🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('178', 'Puerto Rico', '+1-787 and 1-939', '🇵🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('179', 'Qatar', '974', '🇶🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('180', 'Reunion', '262', '🇷🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('181', 'Romania', '40', '🇷🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('182', 'Russia', '7', '🇷🇺');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('183', 'Rwanda', '250', '🇷🇼');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('184', 'Saint Helena', '290', '🇸🇭');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('185', 'Saint Kitts and Nevis', '+1-869', '🇰🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('186', 'Saint Lucia', '+1-758', '🇱🇨');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('187', 'Saint Pierre and Miquelon', '508', '🇵🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('188', 'Saint Vincent and the Grenadines', '+1-784', '🇻🇨');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('189', 'Saint-Barthelemy', '590', '🇧🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('190', 'Saint-Martin (French part)', '590', '🇲🇫');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('191', 'Samoa', '685', '🇼🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('192', 'San Marino', '378', '🇸🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('193', 'Sao Tome and Principe', '239', '🇸🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('194', 'Saudi Arabia', '966', '🇸🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('195', 'Senegal', '221', '🇸🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('196', 'Serbia', '381', '🇷🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('197', 'Seychelles', '248', '🇸🇨');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('198', 'Sierra Leone', '232', '🇸🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('199', 'Singapore', '65', '🇸🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('250', 'Sint Maarten (Dutch part)', '1721', '🇸🇽');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('200', 'Slovakia', '421', '🇸🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('201', 'Slovenia', '386', '🇸🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('202', 'Solomon Islands', '677', '🇸🇧');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('203', 'Somalia', '252', '🇸🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('204', 'South Africa', '27', '🇿🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('205', 'South Georgia', '500', '🇬🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('116', 'South Korea', '82', '🇰🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('206', 'South Sudan', '211', '🇸🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('207', 'Spain', '34', '🇪🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('208', 'Sri Lanka', '94', '🇱🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('209', 'Sudan', '249', '🇸🇩');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('210', 'Suriname', '597', '🇸🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('211', 'Svalbard and Jan Mayen Islands', '47', '🇸🇯');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('213', 'Sweden', '46', '🇸🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('214', 'Switzerland', '41', '🇨🇭');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('215', 'Syria', '963', '🇸🇾');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('216', 'Taiwan', '886', '🇹🇼');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('217', 'Tajikistan', '992', '🇹🇯');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('218', 'Tanzania', '255', '🇹🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('219', 'Thailand', '66', '🇹🇭');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('17', 'The Bahamas', '+1-242', '🇧🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('63', 'Timor-Leste', '670', '🇹🇱');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('220', 'Togo', '228', '🇹🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('221', 'Tokelau', '690', '🇹🇰');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('222', 'Tonga', '676', '🇹🇴');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('223', 'Trinidad and Tobago', '+1-868', '🇹🇹');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('224', 'Tunisia', '216', '🇹🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('225', 'Turkey', '90', '🇹🇷');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('226', 'Turkmenistan', '993', '🇹🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('227', 'Turks and Caicos Islands', '+1-649', '🇹🇨');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('228', 'Tuvalu', '688', '🇹🇻');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('229', 'Uganda', '256', '🇺🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('230', 'Ukraine', '380', '🇺🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('231', 'United Arab Emirates', '971', '🇦🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('232', 'United Kingdom', '44', '🇬🇧');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('233', 'United States', '1', '🇺🇸');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('234', 'United States Minor Outlying Islands', '1', '🇺🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('235', 'Uruguay', '598', '🇺🇾');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('236', 'Uzbekistan', '998', '🇺🇿');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('237', 'Vanuatu', '678', '🇻🇺');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('238', 'Vatican City State (Holy See)', '379', '🇻🇦');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('239', 'Venezuela', '58', '🇻🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('240', 'Vietnam', '84', '🇻🇳');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('241', 'Virgin Islands (British)', '+1-284', '🇻🇬');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('242', 'Virgin Islands (US)', '+1-340', '🇻🇮');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('243', 'Wallis and Futuna Islands', '681', '🇼🇫');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('244', 'Western Sahara', '212', '🇪🇭');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('245', 'Yemen', '967', '🇾🇪');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('246', 'Zambia', '260', '🇿🇲');
INSERT INTO countries (id, name, phone_code, emoji) VALUES ('247', 'Zimbabwe', '263', '🇿🇼');