export const modalityMap = {
  1: "Presencial",
  2: "Remoto",
  3: "Híbrido",
  4: "Flexible",
};

export const contractType = {
  1: "Jornada completa",
  2: "Media jornada",
  3: "Por horas",
  4: "Por proyecto",
  5: "Temporal",
  6: "Freelance",
  7: "Voluntariado",
  8: "Prácticas",
  9: "Otro",
};

export const industriesMap = {
  1: "Administración Pública y Defensa",
  2: "Aeroespacial",
  3: "Agricultura, Silvicultura, Pesca y Caza",
  4: "Alimentos y Bebidas",
  5: "Arte, Entretenimiento y Recreación",
  6: "Automotriz",
  7: "Biotecnología",
  8: "Comercio Mayorista y Minorista",
  9: "Construcción",
  10: "Educación",
  11: "Energía",
  12: "Farmacéutica",
  13: "Finanzas",
  14: "Finanzas y Seguros",
  15: "Hospitalidad y Turismo",
  16: "Industria Manufacturera",
  17: "Información y Comunicaciones",
  18: "Inmobiliarias y Servicios de Alquiler",
  19: "IT",
  20: "Logística y Transporte",
  21: "Marketing",
  22: "Media",
  23: "Medios de Comunicación y Entretenimiento",
  24: "Minería y Metales",
  25: "Petróleo y Gas",
  26: "Productos de Consumo",
  27: "Salud",
  28: "Servicios de Alojamiento y Alimentación",
  29: "Servicios Médicos",
  30: "Servicios Profesionales, Científicos y Técnicos",
  31: "Tecnología de la Información y Telecomunicaciones",
  32: "Textil y Vestimenta",
  33: "Transporte y Almacenamiento",
};
